### PR TITLE
kie-issues#965: Make sure kie-tools is using the latest timestamped SNAPSHOT from Kogito

### PR DESCRIPTION
**Pull request by yesamer**
Closes https://github.com/apache/incubator-kie-issues/issues/965

### CODE REVIEW

**Comment by yesamer** [comment]
@tiagobento It fails in my local  :(

Screenshot 2024-04-08 at 16 50 23

Is maybe something missing in the configuration?

**Comment by thiagoelg** [comment]
Can you share the repository you're using as a base to apply the accelerator?

**Comment by yesamer** [comment]
@thiagoelg https://github.com/yesamer/incubator-kie-sandbox-quarkus-accelerator/

**Comment by thiagoelg** [comment]
Sorry, I meant the project that you're applying the accelerator on top of

**Comment by yesamer** [comment]
@tiagobento Ok I tested it and it works. 
I previously had that error because I didn't change the `gitRepositoryGitRef` to point to my branch `kie-issues#965`.
I changed the `gitRepositoryUrl` only.

With this setup, it works:
Screenshot 2024-04-13 at 15 32 32

**Review by thiagoelg — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
